/**
 * `v1.0.0` tag COMMAND SCRIPT preparer — roadmap/23-release-hardening.md
 * work item 10: "a `v1.0.0` tag COMMAND script (not run)." PREPARE-DON'T-
 * PUBLISH (owner decision): this module only RENDERS shell-script TEXT —
 * it never calls `child_process.exec`/`spawn`/`execFile` on `git tag`
 * itself, and never writes to any file outside a caller-chosen path (which
 * this project's own tests always point at a scratch temp directory, never
 * the real repo root).
 */

export interface TagScriptOptions {
  /** e.g. `"v1.0.0"`. */
  readonly tagName: string;
  /** The commit-ish to tag — `"HEAD"` by default, but a real release cut should pass the exact, frozen release-candidate object ID instead. */
  readonly commitIsh?: string;
  readonly message: string;
  /** Whether the rendered script also pushes the tag to `origin` — defaults to `false` (tag-only; a real release still requires a deliberate, separate, human-reviewed push step per this phase's own "prepare, don't publish" framing). */
  readonly includePush?: boolean;
}

/**
 * Renders (never executes) a small, POSIX-shell `v1.0.0` tag script:
 * `set -euo pipefail`, an annotated `git tag -a <tagName> -m <message>
 * <commitIsh>`, and — only when `includePush` is `true` — a subsequent
 * `git push origin <tagName>`. The rendered text always ends with an
 * explicit comment restating that running this script is a deliberate,
 * separate, human-initiated step this harness itself never takes.
 */
export function prepareTagScript(options: TagScriptOptions): string {
  const commitIsh = options.commitIsh ?? "HEAD";
  const escapedMessage = options.message.replace(/'/g, `'\\''`);
  const lines = [
    "#!/usr/bin/env bash",
    "# PREPARED, NOT EXECUTED — roadmap/23-release-hardening.md work item 10.",
    "# This script was generated by e2e/release's releaseTagScriptPreparer and has never been run",
    "# by that harness. Running it is a deliberate, separate, human-initiated release step.",
    "set -euo pipefail",
    "",
    `git tag -a '${options.tagName}' -m '${escapedMessage}' '${commitIsh}'`,
  ];
  if (options.includePush === true) {
    lines.push(`git push origin '${options.tagName}'`);
  }
  lines.push("", `echo 'Tag ${options.tagName} created locally. Push it deliberately when ready.'`);
  return `${lines.join("\n")}\n`;
}
